### ISSUE TITLE
Use a more general python interpreter location

### ISSUE THREAD

**Issue by mdrasmus** [macarthur-lab/clinvar#1]
Instead of having each python script start with:

```
#!/broad/software/free/Linux/redhat_5_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/bin/python
```

You should use:

```
#!/usr/bin/env python
```

The use of `env` ensures that the "current" python interpreter, wherever it is installed, is used.

**Comment by ericminikel** [comment]
Done! https://github.com/macarthur-lab/clinvar/commit/77efd6b80aefa8e9174bb5d884f0d90885b53951 Good call, thanks for bringing this up.

**Comment by mdrasmus** [comment]
Awesome thanks!
