### ISSUE TITLE
Origin column

### ISSUE THREAD

**Issue by sigven** [macarthur-lab/clinvar#10]
hi,

Thanks for a very useful resource, it simplifies a lot. Would you consider adding the variant origin in the output (for annoation of 'germline,'somatic','de novo' etc.)? It is present in the variant_summary.txt.gz. I guess adding one more variable to join_data.R would work, e.g.:

colnames(txt_extract) = c('measureset_id','symbol','clinical_significance','review_status','hgvs_c','hgvs_p','origin')

best,
Sigve

**Comment by bw2** [comment]
Hi Sigve, 
Since adding another column to the output may break people's scripts, I'm hesitant to do it unless there's  broader interest.

**Comment by bw2** [comment]
@sigven I'm adding ModeOfInheritance and other columns as part of #11 which provide similar information as the origin column.

**Comment by bw2** [comment]
origin column has been added
