### ISSUE TITLE
I would like to have the ModeOfInheritence field in the flatfile. 

### ISSUE THREAD

**Issue by vigneshravi** [macarthur-lab/clinvar#11]
This tool has been very helpful! I would like to have the ModeOfInheritence field pulled into the flatfile. Is there any addendum that you can provide to the script? IS there a way I could customize the columns I want pulled into the flatfile?

**Comment by ericminikel** [comment]
Interesting... is that field new? I haven't seen it before. At a quick glance it looks like there are >80K values in the file, not sure how many unique variants are actually annotated:

```
$ gunzip -c ClinVarFullRelease_2016-08.xml.gz | grep ModeOfInheritance | wc -l
   84328
```

Here are counts of the values in that field:

```
$ gunzip -c ClinVarFullRelease_2016-08.xml.gz | grep ModeOfInheritance | sed 's/.*\">//' | sed 's/<\/.*//' | sort | uniq -c
51208 Autosomal dominant inheritance
22387 Autosomal recessive inheritance
 951 Autosomal unknown
  49 Codominant
 127 Mitochondrial inheritance
 108 Other
  14 Sex-limited autosomal dominant
1209 Somatic mutation
 317 Sporadic
 947 X-linked dominant inheritance
4542 X-linked inheritance
 997 X-linked recessive inheritance
   5 Xlinked NA
  24 Xlinked recessive
  48 Xlinked unknown
   1 Y-linked inheritance
 158 autosomal dominant
  90 autosomal recessive
1146 autosomal unknown
```

@bw2 would you by any chance have time to look into this more? If ClinVar is really going to start filling in this field for a large subset of variants then I imagine this is something we'd want to support.

**Comment by vigneshravi** [comment]
Yes, our group is also interested in getting these fields annotated with the final TSV results. 

THank you!

**Comment by bw2** [comment]
Thanks for pointing out ModeOfInheritence. I've added it to the flatfile and vcf as `inheritance_modes`. The source for it appears to be an optional field in the clinvar submission spreadsheet - currently 19% of variants have it populated.

Also while looking at this, I noticed a couple other fields I hadn't seen before so I added them also:
`disease mechanism` - this might also be coming from the clinvar submissions spreadsheet (though I couldn't find a field for it). 
`prevalence` and `age of onset` - clinvar takes these from orphanet. 
`xrefs` - misc. other cross-reference info and ids packed into this column as key:value;key:value;... 

I've created a pull request with these changes: https://github.com/macarthur-lab/clinvar/pull/12
Any feedback on the code or data files is appreciated.

**Comment by vigneshravi** [comment]
Thank you for the additions. This is definitely helpful. Could you also add the origin info to it? It has germline, de novo and somatic as values for it.

**Comment by vigneshravi** [comment]
I am still getting the old files when I download. Could you point me to the link to download the new files. Thank you!

**Comment by bw2** [comment]
sure, since the table is changing, I'll add this one also.

**Comment by bw2** [comment]
I've added the 'origin' column to PR #12 , and also put in a new 'gold_stars' column which just maps a variant's review_status to a number between 0 - 4. Any feedback is appreciated.

**Comment by vigneshravi** [comment]
Thank you again! This is very useful..
