### ISSUE TITLE
Request: Adding Benign column to the output

### ISSUE THREAD

**Issue by vigneshravi** [macarthur-lab/clinvar#15]
Hi,

Can a benign column and a conflicts column (just like Pathogenic and Conflicting_Pathogenicity) be added to the results?

**Comment by bw2** [comment]
Adding a `benign` column sounds good to me. It'll = 1 if the variant has been asserted benign or likely benign by at least one clinvar submitter. 

As far as another 'conflicted' column, correct me if I'm wrong, but the existing 'conflicted' column should already work as is. It = 1 when there are 'benign / likely benign' and 'pathogenic / like pathogenic' assertions for a variant.

**Comment by vigneshravi** [comment]
That's ture! Just a benign column sounds good.. Thank you!

**Comment by bw2** [comment]
Actually,  `conflicted` will = 1  if/only if  both `pathogenic` = 1 and `benign`= 1 
so the `conflicted` column becomes completely redundant. 
I don't mind keeping it for convenience though.

**Comment by vigneshravi** [comment]
Pathogenic=1 if ClinVar_clinical_significance==Pathogenic or Likely
Pathogenic or Risk Factor
Benign=1 if ClinVar_clinical_significance==Benign or Likely Benign or
Protective
Conflicted=1 if P/LP and B/LB are seen together

Can you also add a column if there is "no conflicts" in
ClinVar_review_status? This will clear up variants where P/LP is reported
by one submitter and uncertain significant is submitted by another
submitter. This column will be a filter on top of the previous three to
really pull out unconflicted pathogenic variants.

Just a thought! Thanks for being super responsive to requests. Really
appreciate this!

**Comment by bw2** [comment]
I think these additional 1/0 columns besides benign are too niche and users that need them can just calculate them from the other fields. Also, 'Risk Factor' and 'Protective' are not currently considered when computing the pathogenic and conflicted columns. I'm not sure if there's a good reason to change this.

**Comment by vigneshravi** [comment]
I see.. I guess the benign for now is good.

**Comment by vigneshravi** [comment]
Thank You!
