### ISSUE TITLE
b38 availability?

### ISSUE THREAD

**Issue by gpcr** [macarthur-lab/clinvar#22]
Hi, I am wondering if the clinvar files are available for b38 version too
Any technichal issues holding it so?

Thanks

**Comment by bw2** [comment]
@gpcr there hasn't been much expressed interest until now, so we'll be adding b38 tables shortly (expect a PR in the next few days).

**Comment by gpcr** [comment]
@bw2 Thanks I will look Fwd to it

**Comment by gpcr** [comment]
@bw2 Thanks for your initiative to add b38
