### ISSUE TITLE
Semi-colon in pathogenic, benign and conflicted columns. Bug?

### ISSUE THREAD

**Issue by ManavalanG** [macarthur-lab/clinvar#26]
Certain rows have values 0 and 1 separated by a semi-colon in columns _pathogenic, benign and conflicted_ of file [clinvar_alleles.tsv.gz](https://github.com/macarthur-lab/clinvar/blob/master/clinvar_alleles.tsv.gz). For example, pathogenic column in line#6704 is _1;0_.  If I am not wrong, these columns must have either 0 or 1 by definition. Is this correct, or am I missing something?

**Edit**: I see these rows always seem to have more than one _measureset_id_. Is this the reason why above-mentioned columns may have multiple values?

**Comment by bw2** [comment]
@ManavalanG this should be fixed now  (I moved the "group by allele" step up in the pipeline) so that these columns are computed after allele-trait pairs and submissions have been collapsed to one record per allele.
