### ISSUE TITLE
add .gitignore File to Repo?

### ISSUE THREAD

**Issue by raymond301** [macarthur-lab/clinvar#27]
Would you be willing to add a .gitignore file to this repo, so when we fork or clone the repository, we don't have to pull down all the data files?

*.tsv
*.tsv.gz
*.tbi

It my be better to host the data files, that result from this code somewhere else, for those users who just want the pre-canned results.

**Comment by raymond301** [comment]
Thanks for clearing up the data files from the code repo.

**Comment by bw2** [comment]
I actually want to add the data back once PR 
https://github.com/macarthur-lab/clinvar/pull/24
gets merged later today. 
Let me create another issue to discuss pros/cons of a data-only repo.
