### ISSUE TITLE
should code be moved to a separate github repo from the data?

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/clinvar#29]
In https://github.com/macarthur-lab/clinvar/issues/27 , @raymond301 suggested putting the clinvar data in a separate github repo from the code. 

It seems simpler to me to keep everything in one place. Does anybody else have a preference on this?

**Comment by ericminikel** [comment]
I like all one place too

**Comment by gpcr** [comment]
I prefer all in one place

**Comment by raymond301** [comment]
I guess, I'm the odd one. I just don't see a purpose in keeping the precomputed results files, with the code used to create those files. If you run the code, it just overwrites them....if you work on the code, they're just in the way.

**Comment by bw2** [comment]
The directory structure is going back to separate `src` and `output` directories, so should help keep the clutter down. Also, next time I work on the code, I'll move the intermediate output files for the pipeline to a separate output dir so they're not mixed in with the code.
