### ISSUE TITLE
RScript crash

### ISSUE THREAD

**Issue by dashgenomics** [macarthur-lab/clinvar#35]
I tried to run the parser with the newest ClinVar may release

I was stuck at the 1.32.  RScript crashed  after a few second of run.

Any idea how it happened?

Thanks for developing the tool.

[May 17 12:05:49]: --> Exec 1.32: Rscript join_data.R variant_summary.txt.gz output_tmp/clinvar_alleles_grouped.single.b37.tsv.gz output_tmp/tmp.2017-05-17_11.05.29.clinvar_alleles_combine[May 17 12:05:49]: --> Exec 1.32: Rscript join_data.R variant_summary.txt.gz output_tmp/clinvar_alleles_grouped.single.b37.tsv.gz output_tmp/tmp.2017-05-17_11.05.29.clinvar_alleles_combined.single.b37.tsv.gz
[May 17 12:05:49]:         Output (last mod N/A): output_tmp/clinvar_alleles_combined.single.b37.tsv.gz  [doesn't exist yet]
[May 17 12:06:13]:         [1] 282106     25
[May 17 12:06:37]:         [1] 634027     30
[May 17 12:06:44]:         Error in write.table(combined, output_table, sep = "\t", row.names = F,  : 
[May 17 12:06:44]:           unimplemented type 'list' in 'EncodeElement'
[May 17 12:06:54]:         $`write.table(combined, output_table, sep = "\\t", row.names = F, col.names = `
[May 17 12:06:54]:         <environment: 0x7fc00382c120>
[May 17 12:06:54]:         attr(,"error.message")
[May 17 12:06:54]:         [1] "Error in write.table(combined, output_table, sep = \"\\t\", row.names = F,  : \n  unimplemented type 'list' in 'EncodeElement'\n"
[May 17 12:06:54]:         attr(,"class")
[May 17 12:06:54]:         [1] "dump.frames"
[May 17 12:06:54]:     Finished 1.32. Running time: 0:01:04.242256 sec.d.single.b37.tsv.gz
[May 17 12:05:49]:         Output (last mod N/A): output_tmp/clinvar_alleles_combined.single.b37.tsv.gz  [doesn't exist yet]
[May 17 12:06:13]:         [1] 282106     25
[May 17 12:06:37]:         [1] 634027     30
[May 17 12:06:44]:         Error in write.table(combined, output_table, sep = "\t", row.names = F,  : 
[May 17 12:06:44]:           unimplemented type 'list' in 'EncodeElement'
[May 17 12:06:54]:         $`write.table(combined, output_table, sep = "\\t", row.names = F, col.names = `
[May 17 12:06:54]:         <environment: 0x7fc00382c120>
[May 17 12:06:54]:         attr(,"error.message")
[May 17 12:06:54]:         [1] "Error in write.table(combined, output_table, sep = \"\\t\", row.names = F,  : \n  unimplemented type 'list' in 'EncodeElement'\n"
[May 17 12:06:54]:         attr(,"class")
[May 17 12:06:54]:         [1] "dump.frames"
[May 17 12:06:54]:     Finished 1.32. Running time: 0:01:04.242256 sec.

**Comment by kristjaneerik** [comment]
See https://github.com/macarthur-lab/clinvar/pull/33#issuecomment-300903892 -- it's an issue with the newest `variant_summary` table, you might want to use an older version.
