### ISSUE TITLE
Wrong gene mapping

### ISSUE THREAD

**Issue by ManavalanG** [macarthur-lab/clinvar#37]
ClinVar record [292157](https://www.ncbi.nlm.nih.gov/clinvar/variation/292157) is about gene MTHFR, but it is wrongly mapped to gene C1orf167 in file [clinvar_alleles.single.b37.tsv.gz](https://github.com/macarthur-lab/clinvar/blob/master/output/b37/single/clinvar_alleles.single.b37.tsv.gz). Coordinate [Chr1:11786191](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A11786191%2D11786191&hgsid=596169855_8p4svWc7tOfa0Vwadc5MmH3UzaAZ) maps to C1orf167 in + strand and MTHFR in - strand. Looks like somewhere in the code, strand variable is overlooked during gene mapping.

**Comment by ManavalanG** [comment]
After a bit more probing, [this file](https://github.com/macarthur-lab/clinvar/files/1098381/not_matching.txt) has all ClinVar IDs with wrong gene mapping. Column 'symbol' was obtained from [clinvar_alleles.single.b37.tsv.gz](https://github.com/macarthur-lab/clinvar/blob/master/output/b37/single/clinvar_alleles.single.b37.tsv.gz), and columns 'geneID_from_refseqID' and 'geneName_from_refseqID' were obtained using RefSeq ID associated with ClinVar IDs.

**Comment by simnim** [comment]
I just looked up the example you Highlighted.
At least for this case it's the same issue I raised earlier. 
[31](https://github.com/macarthur-lab/clinvar/issues/31 )

The first gene symbol in the xml file is C1orf167 and the second is MTHFR.
