### ISSUE TITLE
Augmented tables in output

### ISSUE THREAD

**Issue by balchlab** [macarthur-lab/clinvar#52]
Currently, only the b37/multi folder has augmented tables (with ExAC and GnomAD data). Shouldn't these augmented tables be in each output folder?

**Comment by kristjaneerik** [comment]
https://github.com/macarthur-lab/clinvar/pull/51/files has files for `b37/single` as well.
b38 is trickier as one would have to lift over ExAC/gnomAD and deal with all the quirks of that.

**Comment by balchlab** [comment]
Great, thanks! `b37/single` will work.
