### ISSUE TITLE
Problems with hgvs representation for Clinvar haplotype entries

### ISSUE THREAD

**Issue by jenn1064** [macarthur-lab/clinvar#6]
It looks like the clinvar.tsv file doesn't always represent the correct c. hgvs for Clinvar entries that have multiple c. hgvs as part of the haplotype. And not all haplotypes seem to be represented in the clinvar.tsv file. Could you have a look?

![image](https://cloud.githubusercontent.com/assets/13263329/9119246/82b9071a-3c2a-11e5-9cb6-362821d3a24d.png)

![screen shot 2015-08-06 at 11 07 06 am](https://cloud.githubusercontent.com/assets/13263329/9119428/645dee24-3c2b-11e5-8c75-fc62c35a3c70.png)
![screen shot 2015-08-06 at 11 06 28 am](https://cloud.githubusercontent.com/assets/13263329/9119430/6705d9c0-3c2b-11e5-9b76-b4920ffb3872.png)

**Comment by ericminikel** [comment]
Hi Jenn. Thanks for pointing this out. We did not attempt to include the exhaustive list of HGVS representations that appear in the XML file (and therefore on the ClinVar website). The HGVS representations in our file come from the TXT dump (`variant_summary.txt.gz`) released by ClinVar, and even then, may not be exhaustive, as where the TXT file contains duplicate entries, we randomly discard all but one. I have [added](https://github.com/macarthur-lab/clinvar/commit/1755acff37a3848f564c60747ebd940fe457cba8) a note about this to the README.
