### ISSUE TITLE
mut column

### ISSUE THREAD

**Issue by dakl** [macarthur-lab/clinvar#7]
Hi, 

Thanks for this - very useful. I intend to convert this to a VCF file to use downstream. I can't find any info on what the `mut` columns is. It's value is commonly `ALT`, but sometimes `REF`. What does is mean? 

thanks!

**Comment by dakl** [comment]
I've now made a first version of the converter available at [dakl/macarthur-clinvar-to-vcf](https://github.com/dakl/macarthur-clinvar-to-vcf). Feel free to check it out. It currently ignores the `mut` column form the TSV altogether until I know what to do with it. 

thanks

**Comment by ericminikel** [comment]
`mut` tells you which allele, the reference or alternate, is the one to which the annotations (e.g. pathogenic assertion) refer.

I guess we should add a data dictionary!

**Comment by neilfws** [comment]
What about cases where a variant has two or more alternate alleles? These do not seem to be represented in this TSV file.

**Comment by ericminikel** [comment]
@neilfws they're in there as separate lines, i.e. the dataset is non-unique on chrom, pos, ref:

```
$ cat output/clinvar.tsv | cut -f1,2,3 | uniq -c | sort -nr | head
  15 3  37067119    T
   8 20 62046495    C
   4 X  153296529   G
   4 3  37089131    A
   4 3  37056036    G
   4 2  47702410    G
   4 2  189860905   G
   4 17 41276033    C
   4 17 41244936    G
   4 17 41219627    G
```

**Comment by hujingchu** [comment]
@ericminikel 
hi, how can I find the illustration of determining the 'mut' ? It seems Clinvar has not provide such information?
thanks

**Comment by ericminikel** [comment]
@hujingchu `mut` was originally (still is?) in the ClinVar XML file, parsed here https://github.com/macarthur-lab/clinvar/blob/master/src/parse_clinvar_xml.py#L62 though I hear the XML format has changed and I haven't kept up so I can't speak to whether it is still in there. ask @bw2 -- he's taken over development of this repo.

**Comment by hujingchu** [comment]
@ericminikel thank you, I saw the annotations, the method is a little bit strange.
Looking forward @bw2 's advice.

**Comment by bw2** [comment]
@hujingchu @ericminikel 
After spending some time looking into this, I think the `mut` column is outdated. 
The current spreadsheet for submitting variants to clinvar doesn't have instructions for submitting assertions about the REF allele, so I'll remove the `mut` column from future releases.
