### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by sigven** [macarthur-lab/clinvar#9]
Hi,

I really like this resource, and the job you have put together to make clinvar data available in a clean way. I stumbled into some problems trying to make the workflow work on my own computer, but then you tend to do regular updates of the output.tsv file, which is excellent. Are you planning on any update of this soon?

On beforehand, thanks.

Sigve

**Comment by bw2** [comment]
Hi Sigve, thanks for the reminder. I've just updated the output files.

Best,
-Ben
